scrape_configs:
  - job_name: 'MyAppMetrics'
    # scheme: https
    # tls_config:
    #   insecure_skip_verify: true
    metrics_path: '/actuator/prometheus'
    scrape_interval: 1s
    static_configs:
      - targets: ['prometheus-feeder:8080']
